### ISSUE TITLE
[question] Why no children in the component function

### ISSUE THREAD

**Issue by dwhitney** [spicydonuts/purescript-react-basic-hooks#11]
hi @spicydonuts,

I've got a question: why does the [component funtion](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/src/React/Basic/Hooks.purs#L58) disallow fields named `children` and others? I am using some third party libraries that have components/props with these names, and this requirement is making me jump through some hoops when using hooks that aren't necessary when using regular `react-basic`. 

Thanks!

**Comment by spicydonuts** [comment]
The [v3.0.0]() and [v4.0.0]() release notes explain it a bit, though I should add that info to the docs and/or readme. Do those notes answer your question? Regular `react-basic` doesn't have this issue under normal use, because all the PS props get tunnelled through a nested prop, `$$props`. It can arise from the use of `toReactComponent`, however, so I'll probably address that soon as well.

**Comment by dwhitney** [comment]
Hmm... I hate javascript :)

Ok, I'll write a helper function to rename the fields.

Thanks!

**Comment by spicydonuts** [comment]
`componentWithChildren` is also an option, it just requires a particular type for children so they can be read safely.
