### ISSUE TITLE
Why `component` function has type `Effect (ReactComponent props)` but not `ReactComponent props`

### ISSUE THREAD

**Issue by srghma** [spicydonuts/purescript-react-basic-hooks#12]
e.g. consider writing page for next.js

the `page` function should have type `{} -> JSX` or `ReactComponent {}`

______

Actual:

```purescript
mkCounter :: Effect (ReactComponent {})
mkCounter = do
  component "Counter" \props -> React.do
    counter /\ setCounter <- useState 0
    pure
      $ fragment
          [ R.button
              { onClick: handler_ $ setCounter (_ + 1)
              , children: [ R.text $ "Increment: " <> show counter ]
              }
          ]

mkPage :: Effect (ReactComponent {})
mkPage = do
  counter <- mkCounter

  component "Page" \props -> React.do
    pure
      $ fragment
          [ counter
          , counter
          ]

page :: ReactComponent {}
page = unsafePerformEffect mkPage
```

Expected:

```purescript
counter :: ReactComponent {}
counter = component "Counter" \props -> React.do
  counter /\ setCounter <- useState 0
  pure
    $ fragment
        [ R.button
            { onClick: handler_ $ setCounter (_ + 1)
            , children: [ R.text $ "Increment: " <> show counter ]
            }
        ]

page :: ReactComponent {}
page = component "Page" \props -> React.do
  pure
    $ fragment
        [ counter
        , counter
        ]
```

_________

Do we really need to call `mkCounter()`?

For example, I don't see that example from https://reactjs.org/docs/hooks-overview.html

```js
import React, { useState } from 'react';

function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

was written as

```js
import React, { useState } from 'react';

function mkExample() {
  return function Example() {
    // Declare a new state variable, which we'll call "count"
    const [count, setCount] = useState(0);

    return (
      <div>
        <p>You clicked {count} times</p>
        <button onClick={() => setCount(count + 1)}>
          Click me
        </button>
      </div>
    );
  }
}
```

**Comment by srghma** [comment]
What it would give - easier to use api

**Comment by starper** [comment]
@srghma To answer your question we can look into [source code](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/v4.1.1/src/React/Basic/Hooks.purs#L114), where we will find out that the only reason `component` function is effectful is `unsafeSetDisplayName` function.

Personally, I don't see anything about `unsafeSetDisplayName`'s [implementation](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/v4.1.1/src/React/Basic/Hooks.js#L79) that suggests that it should be effectful. It takes a foreign type `ReactComponent props` (which is just a JS function), updates and then returns it, that's it.

So I agree with you, `component` function should not be effectful, it complicates API for no particular reason.

**Comment by srghma** [comment]
Good that we are on the same page

I would even make `unsafeSetDisplayName` to have type `unsafeSetDisplayName :: (props -> JSX) -> ReactComponent props`

**Comment by spicydonuts** [comment]
It's effectual because React uses function instances as component identity. This is why React generally recommends module-level component definition. Creating component functions during render results in forced unmouting and remounting of the entire tree below that component, even if all the rendered VDOM is the same as the last render and matches the real DOM. This conflicts with PureScript's concepts of equality, i.e. `Just 5 == Just 5` is `true`, even though `unsafeRefEq (Just 5) (Just 5)` returns `false`.

Using `Effect` captures this instance-based side effect so it can be reasoned about in PS. If you write a component "factory" function, it captures the idea that each call produces an entirely different component, regardless of behavior or display name.

You can still choose to hide this detail under the rug using `unsafePerformEffect` around your component definition (ex below), but it's up to you now instead of being hidden in the library because it was too easy to run into this identity issue. Even adding a typeclass constraint to a component definition! Every instance of the glass gets a separate component. This happens in every PS React wrapper I've seen btw, it's just an uncommon use case for small examples.

I still recommend [dealing with effectual component creation directly](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/examples/context/src/Context.purs#L14), but you can still write your example above like this:

```purs
counter :: ReactComponent {}
counter = unsafePerformEffect do
  component "Counter" \props -> React.do
    counter /\ setCounter <- useState 0
    pure
      $ fragment
          [ R.button
              { onClick: handler_ $ setCounter (_ + 1)
              , children: [ R.text $ "Increment: " <> show counter ]
              }
          ]

page :: ReactComponent {}
page = unsafePerformEffect do
  component "Page" \props -> React.do
    pure
      $ fragment
          [ counter
          , counter
          ]
```

Btw, this is [explained briefly in the docs](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/src/React/Basic/Hooks.purs#L54), but if that was confusing or not enough info let me know.

**Comment by starper** [comment]
@spicydonuts OK, it makes sense. I got so used to the idea that `React` is not `PureScript`-friendly and that this _define component as a module-level function_ convention is just a necessary evil, that I completely missed the fact that this weird behavior can be captured by `Effect` monad.
Function which behavior changes based on the context in which it was defined should indeed be effectful.

**Comment by srghma** [comment]
It does make sense
