### ISSUE TITLE
question about targetValue in event

### ISSUE THREAD

**Issue by mananamenos** [spicydonuts/purescript-react-basic-hooks#13]
Hi, https://github.com/lumihq/purescript-react-basic/blob/a81de9964b57b06e23939a784fa18a724261656e/src/React/Basic/DOM/Events.purs#L131

Here I don't understand why the `targetValue` is inside `Maybe String`. For example, if an option inside a select box is selected, it does always have a value. If you could explain a bit the theory behind this, i would really appreciate it. 
When I want to pass the targetValue (which is string), i have to unwrap it from maybe and pass some default value in case it is `Nothing`. However i can't see when it could hold the value `Nothing`.
Thank you

**Comment by spicydonuts** [comment]
This is because not all events are input change events, where the target DOM element has a `value` property. Even the `<input />` element varies, in that checkboxes and radios use the `checked` property. The existing event type is generic, so most of the accessors must be Maybes. It's possible some parts could be typed more specifically, but the solution would be a fair bit more complicated.
