### ISSUE TITLE
`useRef` with an array of refs

### ISSUE THREAD

**Issue by i-am-the-slime** [spicydonuts/purescript-react-basic-hooks#28]
I know how to use `useRef` for a `Nullable` ref to one element. 
Is there a way to achieve something like [this](https://erikmartinjordan.com/multiple-refs-array-hooks)? It looks like I might need some mutable Array for this.

Maybe it's an antipattern in the first case?

**Comment by spicydonuts** [comment]
Hmm.. you could do it if you used FFI to set the ref, because `react-basic` only supports passing a `Ref` as the ref prop, but this multi- example is using React's alternative ref api of passing a callback. Something like `foreign import input :: forall a. ReactComponent { ref :: EffectFn1 (Ref a) Unit, ... }`.

These two options are probably better for most cases, though:

1. The array is for convenience purposes and the number of elements is static. Just call `useRef` multiple times.
1. The list is dynamic, but you can create a component which renders a single input and contains its own `useRef`, then map over your array in the parent component.

**Comment by i-am-the-slime** [comment]
For 2) how would I get the ref back from the child to the parent? With a callback prop to the child?

**Comment by spicydonuts** [comment]
The ref would be hidden in the child and managed using normal props on the child + useEffect. If you really needed to for some reason, the child could have a prop like `innerRef :: Ref` and pass that to the inner dom node instead of creating its own.

**Comment by spicydonuts** [comment]
But then you're kind of back to the original issue

**Comment by spicydonuts** [comment]
Maybe if you explain the use case a bit I can give a more specific suggestion

**Comment by spicydonuts** [comment]
I'm going to close this for now. Feel free to ask if you have any more questions.
