### ISSUE TITLE
R.video dom element

### ISSUE THREAD

**Issue by mananamenos** [spicydonuts/purescript-react-basic-hooks#31]
Hi, why doesn't `React.Basic.DOM.video` have a `controls` attribute? Or should I use/look for this somewhere else?

Thanks

**Comment by spicydonuts** [comment]
It's just an oversight. Most of the types came from a JS library initially, and we've overridden things like this over time here: https://github.com/lumihq/purescript-react-basic-dom/blob/main/codegen/react-html-attributes.json#L858

It looks like it's there. Is it not working? I'm going to close this one here since this is the hooks implementation specifically. Could you open this issue in the repo linked above, maybe with the code that isn't working?

**Comment by mananamenos** [comment]
https://github.com/lumihq/purescript-react-basic-dom/issues/1
