### ISSUE TITLE
useEffect with functions as part of the key

### ISSUE THREAD

**Issue by mattjacobus** [spicydonuts/purescript-react-basic-hooks#5]
Hi, I have a component that gets passed a function via props that sometimes changes.  In my case it's a partially applied function on data that changes but is not currently part of props since this component shouldn't need to know about this data.  I need to use this function in useEffect.  The advice I've read says this function should be included in the dependencies/key of the useEffect call, but I don't see a way to achieve this without including the data (partially applied in the function) in props.

My code looks like this:

```
type Props = 
  { onChange :: Change -> Effect Unit
  , ...
  }

mkComp :: CreateComponent Props
mkComp = do
  component "Comp" \props -> React.do
    ...
    useEffect <somekey> do
      -- set onChange callback from props into javascript component

    useLayoutEffect unit do
      -- create javascript component as child of divRef

    pure $ element (R.unsafeCreateDOMComponent "div") { ref: divRef }

```

Without this useEffect where I set the new callback function into the javascript component, I get an old version of the data.  I've read [here](https://overreacted.io/a-complete-guide-to-useeffect/) that one can use useCallback to wrap up the callback function, but useCallback isn't available in this purescript hooks API.  Should it be?  Or am I thinking about this incorrectly?  

Thanks for the great library!

**Comment by spicydonuts** [comment]
I should probably add `useCallback`. I didn't really understand it when I was initially creating this and haven't technically needed it yet, but it's still part of the API.

For now you can get around it with `useMemoLazy` (I should probably drop `useMemo` and just use `useMemoLazy` while adding `useCallback`):

```purs
-- in the parent that creates the callback
callback <- useMemoLazy (all the callback's deps) \_ -> {- the callback -}
```
```purs
-- in the child component with effects using the prop callback
useEffect (UnsafeReference props.callback) do ...
```

**Comment by spicydonuts** [comment]
How have you found Eq to be on deps? I was a little worried about performance but haven't had problems yet.

**Comment by spicydonuts** [comment]
So I’ve been tinkering with this a bit and I’m conflicted..... 😅

Turns out my `useMemo` is nearly identical to React’s `useCallback` (just need to pass an Eq key separately) and `useMemoLazy` is React’s `useMemo`. What I’m torn on is whether to try to match React’s API exactly or use more “correct” names. What I mean is that `useCallback` is named as a hint for users that the main use case is maintaining function identity, but it really works for any kind of object.

**Comment by spicydonuts** [comment]
(so deciding between renaming to match React or keep the names `useMemo` (possibly confusing since it isn’t the same as React’s) and `useMemoLazy`, or maybe new names like `useEqCache` and `useLazyEqCache` or something about “identity”.....)

**Comment by spicydonuts** [comment]
I ended up sticking with the React names since it's more likely people are familiar with that and this is a React wrapper. I also added [an example](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/examples/memo-callback/src/MemoCallback.purs#L15) for `useCallback`/`useMemo`. Try `0.7` and let me know if you have issues.

I've added `useAff` and `useResetToken` as well.
